#!/usr/bin/env node
// Generate site images with Codex's native image generation (uses your Codex/ChatGPT login, no API key).
// Usage: node scripts/generate-images.mjs <spec.json> <outDir> [--parallel 3]
// Spec: { "style": "shared style text", "images": [{ "slot": "hero", "prompt": "...", "alt": "..." }] }
// Each image is generated by Codex with its shell tool disabled in a read-only sandbox, collected by thread id,
// validated (PNG magic bytes + dimensions), then compressed to JPEG with sharp. Prompts come only from the spec.
import { spawn } from 'node:child_process';
import { mkdtemp, readdir, readFile, rm, writeFile, mkdir } from 'node:fs/promises';
import { homedir, tmpdir } from 'node:os';
import path from 'node:path';
import sharp from 'sharp';

const [specPath, outDir] = process.argv.slice(2);
const parallel = Number(process.argv[process.argv.indexOf('--parallel') + 1]) || 3;
if (!specPath || !outDir) { console.error('usage: generate-images.mjs <spec.json> <outDir> [--parallel N]'); process.exit(2); }

const spec = JSON.parse(await readFile(specPath, 'utf8'));
const SAFE_SLOT = /^[a-z0-9][a-z0-9-]{0,40}$/;
await mkdir(outDir, { recursive: true });

// Hardened: Codex's shell tool is disabled and the sandbox is read-only, so it can only generate an image.
// The PNG is collected from Codex's own output folder by thread id.
const codexHome = process.env.CODEX_HOME || path.join(homedir(), '.codex');
const THREAD_ID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;

function runCodex(cwd, prompt) {
  return new Promise((resolve, reject) => {
    const child = spawn('codex', ['exec', '--skip-git-repo-check', '--ephemeral', '--ignore-user-config', '--json', '-s', 'read-only', '--disable', 'shell_tool', '-C', cwd, prompt], { stdio: ['ignore', 'pipe', 'ignore'] });
    const timer = setTimeout(() => { child.kill('SIGKILL'); reject(new Error('timed out')); }, 280_000);
    let buf = '', threadId = '';
    child.stdout.on('data', (chunk) => {
      buf += chunk;
      let nl;
      while ((nl = buf.indexOf('\n')) >= 0) {
        const line = buf.slice(0, nl); buf = buf.slice(nl + 1);
        try { const e = JSON.parse(line); if (e.type === 'thread.started' && THREAD_ID.test(e.thread_id)) threadId = e.thread_id; } catch {}
      }
    });
    child.on('error', (e) => { clearTimeout(timer); reject(e); });
    child.on('exit', (code) => {
      clearTimeout(timer);
      if (code === 0 && threadId) resolve(threadId);
      else reject(new Error(`codex exited ${code}`));
    });
  });
}

async function generate({ slot, prompt }) {
  if (!SAFE_SLOT.test(slot)) throw new Error(`bad slot name: ${slot}`);
  const dir = await mkdtemp(path.join(tmpdir(), 'imggen-'));
  let threadId = '';
  try {
    const full = `Use your native image generation tool to create exactly ONE image. Do not run commands or read files. ${spec.style ?? ''} ${prompt} No text, logos or watermarks. Reply with only the word done.`;
    for (let attempt = 1; attempt <= 2; attempt++) {
      try {
        threadId = await runCodex(dir, full);
        const folder = path.join(codexHome, 'generated_images', threadId);
        const pngs = (await readdir(folder)).filter((n) => n.endsWith('.png')).sort();
        if (!pngs.length) throw new Error('no image produced');
        const png = await readFile(path.join(folder, pngs[pngs.length - 1]));
        if (png.subarray(0, 8).toString('hex') !== '89504e470d0a1a0a') throw new Error('not a PNG');
        const meta = await sharp(png).metadata();
        if (!meta.width || meta.width < 1000) throw new Error(`too small: ${meta.width}px`);
        const jpg = await sharp(png).resize({ width: 1600, withoutEnlargement: true }).jpeg({ quality: 82, mozjpeg: true }).toBuffer();
        await writeFile(path.join(outDir, `${slot}.jpg`), jpg);
        return { slot, bytes: jpg.length, from: `${meta.width}x${meta.height}`, attempt };
      } catch (e) { if (attempt === 2) throw e; }
    }
  } finally {
    await rm(dir, { recursive: true, force: true });
    if (threadId) await rm(path.join(codexHome, 'generated_images', threadId), { recursive: true, force: true });
  }
}

const queue = [...spec.images];
const results = [];
async function worker() {
  while (queue.length) {
    const item = queue.shift();
    const started = Date.now();
    try { const r = await generate(item); results.push({ ok: true, ...r, alt: item.alt, secs: Math.round((Date.now() - started) / 1000) }); console.log(`OK   ${item.slot} ${r.from} -> ${Math.round(r.bytes / 1024)}KB (${Math.round((Date.now() - started) / 1000)}s)`); }
    catch (e) { results.push({ ok: false, slot: item.slot, error: e.message }); console.log(`FAIL ${item.slot}: ${e.message}`); }
  }
}
await Promise.all(Array.from({ length: Math.min(parallel, queue.length) }, worker));
await writeFile(path.join(outDir, 'manifest.json'), JSON.stringify({ generator: 'codex native image generation', aiGenerated: true, images: results }, null, 2));
console.log(`done: ${results.filter(r => r.ok).length}/${results.length} images in ${outDir}`);
process.exit(results.every(r => r.ok) ? 0 : 1);
